=head1 SCHEMA CLASS

L<Bio::Chado::Schema> - root module of this package

=head1 CHADO MODULE

Composite - A collection of bridge codes that have multiple dependancies
          so they don't happily go where is most obvious

=head1 CLASSES

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Composite::AllFeatureNames>

L<Bio::Chado::Schema::Composite::Dfeatureloc>

L<Bio::Chado::Schema::Composite::FLoc>

L<Bio::Chado::Schema::Composite::FType>

L<Bio::Chado::Schema::Composite::FeatureContains>

L<Bio::Chado::Schema::Composite::FeatureDifference>

L<Bio::Chado::Schema::Composite::FeatureDisjoint>

L<Bio::Chado::Schema::Composite::FeatureDistance>

L<Bio::Chado::Schema::Composite::FeatureIntersection>

L<Bio::Chado::Schema::Composite::FeatureMeets>

L<Bio::Chado::Schema::Composite::FeatureMeetsOnSameStrand>

L<Bio::Chado::Schema::Composite::FeatureUnion>

L<Bio::Chado::Schema::Composite::FeaturesetMeets>

L<Bio::Chado::Schema::Composite::FnrType>

L<Bio::Chado::Schema::Composite::FpKey>

L<Bio::Chado::Schema::Composite::Gff3atts>

L<Bio::Chado::Schema::Composite::Gff3view>

L<Bio::Chado::Schema::Composite::Gffatts>

=cut
