=head1 SCHEMA CLASS

L<Bio::Chado::Schema> - root module of this package

=head1 CHADO MODULE

Contact - model persons, institutes, groups, organizations, etc

=head1 CLASSES

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Contact::Contact>

L<Bio::Chado::Schema::Contact::ContactRelationship>

=cut
