=head1 NAME

Bio::Chado::Schema::Cv - Controlled vocabularies and ontologies

=head1 CHADO MODULE

Classes in this namespace correspond to tables and views in the
Chado Cv module.

=head1 CLASSES

These classes are part of the L<Bio::Chado::Schema> distribution.

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Cv::CommonAncestorCvterm>

L<Bio::Chado::Schema::Cv::CommonDescendantCvterm>

L<Bio::Chado::Schema::Cv::Cv>

L<Bio::Chado::Schema::Cv::CvCvtermCount>

L<Bio::Chado::Schema::Cv::CvCvtermCountWithObs>

L<Bio::Chado::Schema::Cv::CvLeaf>

L<Bio::Chado::Schema::Cv::CvLinkCount>

L<Bio::Chado::Schema::Cv::CvPathCount>

L<Bio::Chado::Schema::Cv::CvRoot>

L<Bio::Chado::Schema::Cv::Cvterm>

L<Bio::Chado::Schema::Cv::CvtermDbxref>

L<Bio::Chado::Schema::Cv::CvtermRelationship>

L<Bio::Chado::Schema::Cv::Cvtermpath>

L<Bio::Chado::Schema::Cv::Cvtermprop>

L<Bio::Chado::Schema::Cv::Cvtermsynonym>

L<Bio::Chado::Schema::Cv::Dbxrefprop>

L<Bio::Chado::Schema::Cv::StatsPathsToRoot>

=cut
