=head1 SCHEMA CLASS

L<Bio::Chado::Schema> - root module of this package

=head1 CHADO MODULE

Cv - Controlled vocabularies and ontologies

=head1 CLASSES

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Cv::CommonAncestorCvterm>

L<Bio::Chado::Schema::Cv::CommonDescendantCvterm>

L<Bio::Chado::Schema::Cv::Cv>

L<Bio::Chado::Schema::Cv::CvCvtermCount>

L<Bio::Chado::Schema::Cv::CvCvtermCountWithObs>

L<Bio::Chado::Schema::Cv::CvLeaf>

L<Bio::Chado::Schema::Cv::CvLinkCount>

L<Bio::Chado::Schema::Cv::CvPathCount>

L<Bio::Chado::Schema::Cv::CvRoot>

L<Bio::Chado::Schema::Cv::Cvterm>

L<Bio::Chado::Schema::Cv::CvtermDbxref>

L<Bio::Chado::Schema::Cv::CvtermRelationship>

L<Bio::Chado::Schema::Cv::Cvtermpath>

L<Bio::Chado::Schema::Cv::Cvtermprop>

L<Bio::Chado::Schema::Cv::Cvtermsynonym>

L<Bio::Chado::Schema::Cv::Dbxrefprop>

L<Bio::Chado::Schema::Cv::StatsPathsToRoot>

=cut
