=head1 NAME

Bio::Chado::Schema::Library - For describing molecular libraries

=head1 CHADO MODULE

Classes in this namespace correspond to tables and views in the
Chado Library module.

=head1 CLASSES

These classes are part of the L<Bio::Chado::Schema> distribution.

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Library::Library>

L<Bio::Chado::Schema::Library::LibraryCvterm>

L<Bio::Chado::Schema::Library::LibraryDbxref>

L<Bio::Chado::Schema::Library::LibraryFeature>

L<Bio::Chado::Schema::Library::LibraryPub>

L<Bio::Chado::Schema::Library::LibrarySynonym>

L<Bio::Chado::Schema::Library::Libraryprop>

L<Bio::Chado::Schema::Library::LibrarypropPub>

=cut
