=head1 SCHEMA CLASS

L<Bio::Chado::Schema> - root module of this package

=head1 CHADO MODULE

Map - Non-sequence maps: genetic, radiation hybrid, cytogenetic, etc

=head1 CLASSES

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Map::Featuremap>

L<Bio::Chado::Schema::Map::FeaturemapPub>

L<Bio::Chado::Schema::Map::Featurepos>

L<Bio::Chado::Schema::Map::Featurerange>

=cut
