=head1 NAME

Bio::Chado::Schema::Stock - For tracking stock collections

=head1 CHADO MODULE

Classes in this namespace correspond to tables and views in the
Chado Stock module.

=head1 CLASSES

These classes are part of the L<Bio::Chado::Schema> distribution.

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Stock::Stock>

L<Bio::Chado::Schema::Stock::StockCvterm>

L<Bio::Chado::Schema::Stock::StockDbxref>

L<Bio::Chado::Schema::Stock::StockGenotype>

L<Bio::Chado::Schema::Stock::StockPub>

L<Bio::Chado::Schema::Stock::StockRelationship>

L<Bio::Chado::Schema::Stock::StockRelationshipPub>

L<Bio::Chado::Schema::Stock::Stockcollection>

L<Bio::Chado::Schema::Stock::StockcollectionStock>

L<Bio::Chado::Schema::Stock::Stockcollectionprop>

L<Bio::Chado::Schema::Stock::Stockprop>

L<Bio::Chado::Schema::Stock::StockpropPub>

=cut
